/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeyGrabber */

#ifndef _Included_KeyGrabber
#define _Included_KeyGrabber
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KeyGrabber
 * Method:    listen
 * Signature: ()V
 */
JNIEXPORT void JNICALL _Java_KeyGrabber_listen
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
